name: Feature Request
description: File a feature request
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Background Work
      description: Yes, I searched the following areas for a prior feature/solution to this problem.

  - type: textarea
    attributes:
      label: Feature Description
      description: Description of desired feature.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Motivating Example
      description: A concise example demonstrating the feature.
    validations:
      required: true
